# Generated by Django 3.1.4 on 2021-01-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20210103_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('item1_size', models.CharField(blank=True, choices=[('NA', 'Non Applicable'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], max_length=2, null=True)),
                ('item2_size', models.CharField(blank=True, choices=[('NA', 'Non Applicable'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], max_length=2, null=True)),
                ('item3_size', models.CharField(blank=True, choices=[('NA', 'Non Applicable'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], max_length=2, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saving', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('item1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category_item1', to='products.category')),
                ('item2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category_item2', to='products.category')),
                ('item3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category_item3', to='products.category')),
            ],
        ),
    ]
