# Generated by Django 3.1.4 on 2021-01-17 15:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default='tests'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='item1_size',
            field=models.CharField(blank=True, choices=[('NA', 'Non Applicable'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='item2_size',
            field=models.CharField(blank=True, choices=[('NA', 'Non Applicable'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='item3_size',
            field=models.CharField(blank=True, choices=[('NA', 'Non Applicable'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='offer',
            name='saving',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
