# Generated by Django 3.1.4 on 2021-03-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210214_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='Null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
