# Generated by Django 3.1.4 on 2020-12-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_pizza', models.BooleanField(blank=True, default=False, null=True)),
                ('has_sizes', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('dough', models.CharField(blank=True, choices=[('classic', 'classic'), ('thin', 'thin'), ('stuffed', 'stuffed')], default='classic', max_length=254, null=True)),
                ('sauce', models.CharField(blank=True, choices=[('tomato', 'tomato'), ('bbq', 'bbq'), ('garlic', 'garlic')], default='tomato', max_length=254, null=True)),
                ('cheese', models.CharField(blank=True, choices=[('mozzarella', 'mozzarella'), ('cheddar', 'cheddar'), ('vegan', 'vegan')], default='mozzarella', max_length=254, null=True)),
                ('pepperoni', models.BooleanField(blank=True, default=False, null=True)),
                ('bacon', models.BooleanField(blank=True, default=False, null=True)),
                ('sausage', models.BooleanField(blank=True, default=False, null=True)),
                ('ham', models.BooleanField(blank=True, default=False, null=True)),
                ('mushroom', models.BooleanField(blank=True, default=False, null=True)),
                ('pepper', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField()),
                ('is_premium', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
