# Generated by Django 3.1.4 on 2021-01-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201230_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dough',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('thin', 'Thin'), ('stuffed', 'Stuffed')], default='classic', max_length=254, null=True),
        ),
    ]
