# Generated by Django 3.1.4 on 2021-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210118_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bacon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='chicken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='chilli',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='chorizo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_cheese',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='ham',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='key_lime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='meatball',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='mushroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='onion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pepper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pepperoni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pineapple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sausage',
            field=models.BooleanField(default=False),
        ),
    ]
