# Generated by Django 3.1.4 on 2021-01-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210118_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cheese',
            field=models.CharField(blank=True, choices=[('mozzarella', 'Mozzarella'), ('cheddar', 'Cheddar'), ('vegan', 'Vegan')], default='mozzarella', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sauce',
            field=models.CharField(blank=True, choices=[('tomato', 'Tomato'), ('bbq', 'BBQ'), ('garlic', 'Garlic')], default='tomato', max_length=254, null=True),
        ),
    ]
