# Generated by Django 3.1.4 on 2021-02-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210214_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='bacon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chicken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chilli',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chorizo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_cheese',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ham',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key_lime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meatball',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mushroom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='onion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pepper',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pepperoni',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pineapple',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sausage',
        ),
        migrations.AddField(
            model_name='product',
            name='is_orignal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Default', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='products.Toppings'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cheese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cheese'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.dough'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sauce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sauce'),
        ),
    ]
