# Generated by Django 3.1.4 on 2021-02-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210216_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='dough',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], max_length=2, null=True),
        ),
    ]
