# Generated by Django 3.1.4 on 2021-02-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_dough_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dough',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dough',
            name='size',
        ),
    ]
