# Generated by Django 3.1.4 on 2021-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
